In [1]:
from pybaseball import statcast
import pandas as pd
import numpy as np

In [2]:
data = statcast('2019-04-01', '2019-09-07')
data.head()

This is a large query, it may take a moment to complete
Completed sub-query from 2019-04-01 to 2019-04-06
Completed sub-query from 2019-04-07 to 2019-04-12
Completed sub-query from 2019-04-13 to 2019-04-18
Completed sub-query from 2019-04-19 to 2019-04-24
Completed sub-query from 2019-04-25 to 2019-04-30
Completed sub-query from 2019-05-01 to 2019-05-06
Completed sub-query from 2019-05-07 to 2019-05-12
Completed sub-query from 2019-05-13 to 2019-05-18
Completed sub-query from 2019-05-19 to 2019-05-24
Completed sub-query from 2019-05-25 to 2019-05-30
Completed sub-query from 2019-05-31 to 2019-06-05
Completed sub-query from 2019-06-06 to 2019-06-11
Completed sub-query from 2019-06-12 to 2019-06-17
Completed sub-query from 2019-06-18 to 2019-06-23
Completed sub-query from 2019-06-24 to 2019-06-29
Completed sub-query from 2019-06-30 to 2019-07-05
Completed sub-query from 2019-07-06 to 2019-07-11
Completed sub-query from 2019-07-12 to 2019-07-17
Completed sub-query from 2019-07-18 to 2019-

index pitch_type  game_date  release_speed  release_pos_x  release_pos_z  \
0     75         SI 2019-09-07           94.5        -1.5179         5.7863   
1     80         SL 2019-09-07           88.2        -1.3649         5.8144   
2     90         SI 2019-09-07           94.7        -1.2361         5.8325   
3     94         CH 2019-09-07           88.8        -1.4757         5.8277   
4    103         SI 2019-09-07           94.1        -1.3328         5.7909   

        player_name    batter   pitcher  events  ... home_score  away_score  \
0  Brandon Kintzler  592885.0  445213.0  double  ...        2.0         2.0   
1  Brandon Kintzler  592885.0  445213.0     NaN  ...        2.0         2.0   
2  Brandon Kintzler  592885.0  445213.0     NaN  ...        2.0         2.0   
3  Brandon Kintzler  592885.0  445213.0     NaN  ...        2.0         2.0   
4  Brandon Kintzler  592885.0  445213.0     NaN  ...        2.0         2.0   

   bat_score  fld_score  post_away_score  post_home_score post_bat_score  \
0        2.0        2.0              2.0              2.0            2.0   
1        2.0        2.0              2.0              2.0            2.0   
2        2.0        2.0              2.0              2.0            2.0   
3        2.0        2.0              2.0              2.0            2.0   
4        2.0        2.0              2.0              2.0            2.0   

  post_fld_score if_fielding_alignment of_fielding_alignment  
0            2.0              Standard             Strategic  
1            2.0              Standard             Strategic  
2            2.0              Standard             Strategic  
3            2.0              Standard             Strategic  
4            2.0              Standard             Strategic  

[5 rows x 90 columns]

In [3]:
'''
from pybaseball import statcast_pitcher
from pybaseball import playerid_lookup

pid = playerid_lookup('odorizzi','jake')

# get all available data
data = statcast_pitcher('2019-03-01', '2019-04-10', player_id = pid)
data.head()
'''

"\nfrom pybaseball import statcast_pitcher\nfrom pybaseball import playerid_lookup\n\npid = playerid_lookup('odorizzi','jake')\n\n# get all available data\ndata = statcast_pitcher('2019-03-01', '2019-04-10', player_id = pid)\ndata.head()\n"

In [5]:
data = data[["pitch_type", "bat_score", "fld_score", "on_3b", "on_2b", "on_1b", "outs_when_up", "inning", "inning_topbot", "pitch_number", "p_throws", "balls", "strikes", "stand", "batter", "release_speed"]]
data.head()

pitch_type  bat_score  fld_score  on_3b  on_2b     on_1b  outs_when_up  \
0         SI        2.0        2.0    NaN    NaN  592122.0           2.0   
1         SL        2.0        2.0    NaN    NaN  592122.0           2.0   
2         SI        2.0        2.0    NaN    NaN  592122.0           2.0   
3         CH        2.0        2.0    NaN    NaN  592122.0           2.0   
4         SI        2.0        2.0    NaN    NaN  592122.0           2.0   

   inning inning_topbot  pitch_number p_throws  balls  strikes stand  \
0     9.0           Bot           6.0        R    2.0      2.0     L   
1     9.0           Bot           5.0        R    1.0      2.0     L   
2     9.0           Bot           4.0        R    1.0      2.0     L   
3     9.0           Bot           3.0        R    0.0      2.0     L   
4     9.0           Bot           2.0        R    0.0      1.0     L   

     batter  release_speed  
0  592885.0           94.5  
1  592885.0           88.2  
2  592885.0           94.7  
3  592885.0           88.8  
4  592885.0           94.1

In [6]:
data.tail()

pitch_type  bat_score  fld_score  on_3b  on_2b     on_1b  outs_when_up  \
626278         FF        0.0        0.0    NaN    NaN  456715.0           0.0   
626279         FF        0.0        0.0    NaN    NaN       NaN           0.0   
626280         FF        0.0        0.0    NaN    NaN       NaN           0.0   
626281         FF        0.0        0.0    NaN    NaN       NaN           0.0   
626282         FF        0.0        0.0    NaN    NaN       NaN           0.0   

        inning inning_topbot  pitch_number p_throws  balls  strikes stand  \
626278     1.0           Top           1.0        R    0.0      0.0     L   
626279     1.0           Top           4.0        R    3.0      0.0     R   
626280     1.0           Top           3.0        R    2.0      0.0     R   
626281     1.0           Top           2.0        R    1.0      0.0     R   
626282     1.0           Top           1.0        R    0.0      0.0     R   

          batter  release_speed  
626278  592885.0           89.8  
626279  456715.0           90.3  
626280  456715.0           91.1  
626281  456715.0           90.1  
626282  456715.0           90.3

In [7]:
data[["on_3b", "on_2b", "on_1b"]] = data[["on_3b", "on_2b", "on_1b"]].replace(np.nan, 0)
data.loc[data.on_3b > 0, "on_3b"] = 1
data.loc[data.on_2b > 0, "on_2b"] = 1
data.loc[data.on_1b > 0, "on_1b"] = 1
data = data.dropna()
data.head()

/home/parker/.local/lib/python3.6/site-packages/pandas/core/frame.py:2963: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/home/parker/.local/lib/python3.6/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


pitch_type  bat_score  fld_score  on_3b  on_2b  on_1b  outs_when_up  inning  \
0         SI        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
1         SL        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
2         SI        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
3         CH        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
4         SI        2.0        2.0    0.0    0.0    1.0           2.0     9.0   

  inning_topbot  pitch_number p_throws  balls  strikes stand    batter  \
0           Bot           6.0        R    2.0      2.0     L  592885.0   
1           Bot           5.0        R    1.0      2.0     L  592885.0   
2           Bot           4.0        R    1.0      2.0     L  592885.0   
3           Bot           3.0        R    0.0      2.0     L  592885.0   
4           Bot           2.0        R    0.0      1.0     L  592885.0   

   release_speed  
0           94.5  
1           88.2  
2           94.7  
3           88.8  
4           94.1

In [8]:
data["prev_pitch"] = data["pitch_type"].shift(-1)
data["prev_batter"] = data["batter"].shift(-1)
data["release_speed"] = data["release_speed"].shift(-1)

def filterAB(row):
    if row["batter"] == row["prev_batter"]:
        return row["prev_pitch"]
    else:
        return "NB"
    
def filterSpeed(row):
    if row["batter"] == row["prev_batter"]:
        return row["release_speed"]
    else:
        return 0

data["prev_pitch"] = data.apply(lambda row: filterAB(row), axis = 1)
data["release_speed"] = data.apply(lambda row: filterSpeed(row), axis=1)
data

pitch_type  bat_score  fld_score  on_3b  on_2b  on_1b  outs_when_up  \
0              SI        2.0        2.0    0.0    0.0    1.0           2.0   
1              SL        2.0        2.0    0.0    0.0    1.0           2.0   
2              SI        2.0        2.0    0.0    0.0    1.0           2.0   
3              CH        2.0        2.0    0.0    0.0    1.0           2.0   
4              SI        2.0        2.0    0.0    0.0    1.0           2.0   
...           ...        ...        ...    ...    ...    ...           ...   
626278         FF        0.0        0.0    0.0    0.0    1.0           0.0   
626279         FF        0.0        0.0    0.0    0.0    0.0           0.0   
626280         FF        0.0        0.0    0.0    0.0    0.0           0.0   
626281         FF        0.0        0.0    0.0    0.0    0.0           0.0   
626282         FF        0.0        0.0    0.0    0.0    0.0           0.0   

        inning inning_topbot  pitch_number p_throws  balls  strikes stand  \
0          9.0           Bot           6.0        R    2.0      2.0     L   
1          9.0           Bot           5.0        R    1.0      2.0     L   
2          9.0           Bot           4.0        R    1.0      2.0     L   
3          9.0           Bot           3.0        R    0.0      2.0     L   
4          9.0           Bot           2.0        R    0.0      1.0     L   
...        ...           ...           ...      ...    ...      ...   ...   
626278     1.0           Top           1.0        R    0.0      0.0     L   
626279     1.0           Top           4.0        R    3.0      0.0     R   
626280     1.0           Top           3.0        R    2.0      0.0     R   
626281     1.0           Top           2.0        R    1.0      0.0     R   
626282     1.0           Top           1.0        R    0.0      0.0     R   

          batter  release_speed prev_pitch  prev_batter  
0       592885.0           88.2         SL     592885.0  
1       592885.0           94.7         SI     592885.0  
2       592885.0           88.8         CH     592885.0  
3       592885.0           94.1         SI     592885.0  
4       592885.0           93.1         SI     592885.0  
...          ...            ...        ...          ...  
626278  592885.0            0.0         NB     456715.0  
626279  456715.0           91.1         FF     456715.0  
626280  456715.0           90.1         FF     456715.0  
626281  456715.0           90.3         FF     456715.0  
626282  456715.0            0.0         NB          NaN  

[622773 rows x 18 columns]

In [9]:
data = data.drop("prev_batter", 1)
data = data.drop("batter", 1)
data

pitch_type  bat_score  fld_score  on_3b  on_2b  on_1b  outs_when_up  \
0              SI        2.0        2.0    0.0    0.0    1.0           2.0   
1              SL        2.0        2.0    0.0    0.0    1.0           2.0   
2              SI        2.0        2.0    0.0    0.0    1.0           2.0   
3              CH        2.0        2.0    0.0    0.0    1.0           2.0   
4              SI        2.0        2.0    0.0    0.0    1.0           2.0   
...           ...        ...        ...    ...    ...    ...           ...   
626278         FF        0.0        0.0    0.0    0.0    1.0           0.0   
626279         FF        0.0        0.0    0.0    0.0    0.0           0.0   
626280         FF        0.0        0.0    0.0    0.0    0.0           0.0   
626281         FF        0.0        0.0    0.0    0.0    0.0           0.0   
626282         FF        0.0        0.0    0.0    0.0    0.0           0.0   

        inning inning_topbot  pitch_number p_throws  balls  strikes stand  \
0          9.0           Bot           6.0        R    2.0      2.0     L   
1          9.0           Bot           5.0        R    1.0      2.0     L   
2          9.0           Bot           4.0        R    1.0      2.0     L   
3          9.0           Bot           3.0        R    0.0      2.0     L   
4          9.0           Bot           2.0        R    0.0      1.0     L   
...        ...           ...           ...      ...    ...      ...   ...   
626278     1.0           Top           1.0        R    0.0      0.0     L   
626279     1.0           Top           4.0        R    3.0      0.0     R   
626280     1.0           Top           3.0        R    2.0      0.0     R   
626281     1.0           Top           2.0        R    1.0      0.0     R   
626282     1.0           Top           1.0        R    0.0      0.0     R   

        release_speed prev_pitch  
0                88.2         SL  
1                94.7         SI  
2                88.8         CH  
3                94.1         SI  
4                93.1         SI  
...               ...        ...  
626278            0.0         NB  
626279           91.1         FF  
626280           90.1         FF  
626281           90.3         FF  
626282            0.0         NB  

[622773 rows x 16 columns]

In [10]:
data["pitch_type"].unique()

array(['SI', 'SL', 'CH', 'FF', 'FC', 'KC', 'FS', 'FT', 'CU', 'EP', 'FO',
       'KN'], dtype=object)

In [11]:
data["pitch_type"].value_counts()

FF    225666
SL    109966
CH     68736
CU     54816
FT     52843
SI     47805
FC     40209
KC     13336
FS      9120
KN       200
EP        40
FO        36
Name: pitch_type, dtype: int64

In [12]:
data["prev_pitch"].value_counts()

FF    171296
NB    158579
SL     81227
CH     49597
CU     42205
FT     38405
SI     34849
FC     29706
KC     10079
FS      6634
KN       150
FO        25
EP        21
Name: prev_pitch, dtype: int64

In [13]:
data = pd.concat([data,pd.get_dummies(data["prev_pitch"], prefix='prev_pitch')],axis=1)
data = pd.concat([data,pd.get_dummies(data["p_throws"], prefix='pitcher_throws')],axis=1)
data = pd.concat([data,pd.get_dummies(data["stand"], prefix='batter_stands')],axis=1)
data = data.drop(['inning_topbot', 'p_throws', 'stand', 'prev_pitch'], axis = 1)
data.head(10)

pitch_type  bat_score  fld_score  on_3b  on_2b  on_1b  outs_when_up  inning  \
0         SI        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
1         SL        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
2         SI        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
3         CH        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
4         SI        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
5         SI        2.0        2.0    0.0    0.0    1.0           2.0     9.0   
6         CH        2.0        2.0    0.0    0.0    1.0           1.0     9.0   
7         CH        2.0        2.0    0.0    0.0    1.0           1.0     9.0   
8         CH        2.0        2.0    0.0    0.0    1.0           1.0     9.0   
9         CH        2.0        2.0    0.0    0.0    1.0           1.0     9.0   

   pitch_number  balls  ...  prev_pitch_FT  prev_pitch_KC  prev_pitch_KN  \
0           6.0    2.0  ...              0              0              0   
1           5.0    1.0  ...              0              0              0   
2           4.0    1.0  ...              0              0              0   
3           3.0    0.0  ...              0              0              0   
4           2.0    0.0  ...              0              0              0   
5           1.0    0.0  ...              0              0              0   
6           6.0    3.0  ...              0              0              0   
7           5.0    2.0  ...              0              0              0   
8           4.0    2.0  ...              0              0              0   
9           3.0    1.0  ...              0              0              0   

   prev_pitch_NB  prev_pitch_SI  prev_pitch_SL  pitcher_throws_L  \
0              0              0              1                 0   
1              0              1              0                 0   
2              0              0              0                 0   
3              0              1              0                 0   
4              0              1              0                 0   
5              1              0              0                 0   
6              0              0              0                 0   
7              0              0              0                 0   
8              0              0              0                 0   
9              0              0              0                 0   

   pitcher_throws_R  batter_stands_L  batter_stands_R  
0                 1                1                0  
1                 1                1                0  
2                 1                1                0  
3                 1                1                0  
4                 1                1                0  
5                 1                1                0  
6                 1                1                0  
7                 1                1                0  
8                 1                1                0  
9                 1                1                0  

[10 rows x 29 columns]

## Create Fastball/No Fastball Dataset

In [14]:
fbData = data.copy()

def filterFB(row):
    if row["pitch_type"] == 'FF' or row["pitch_type"] == 'FT':
        return 1
    else:
        return 0

fbData["pitch_type"] = fbData.apply(lambda row: filterFB(row), axis = 1)

fbData

pitch_type  bat_score  fld_score  on_3b  on_2b  on_1b  outs_when_up  \
0                0        2.0        2.0    0.0    0.0    1.0           2.0   
1                0        2.0        2.0    0.0    0.0    1.0           2.0   
2                0        2.0        2.0    0.0    0.0    1.0           2.0   
3                0        2.0        2.0    0.0    0.0    1.0           2.0   
4                0        2.0        2.0    0.0    0.0    1.0           2.0   
...            ...        ...        ...    ...    ...    ...           ...   
626278           1        0.0        0.0    0.0    0.0    1.0           0.0   
626279           1        0.0        0.0    0.0    0.0    0.0           0.0   
626280           1        0.0        0.0    0.0    0.0    0.0           0.0   
626281           1        0.0        0.0    0.0    0.0    0.0           0.0   
626282           1        0.0        0.0    0.0    0.0    0.0           0.0   

        inning  pitch_number  balls  ...  prev_pitch_FT  prev_pitch_KC  \
0          9.0           6.0    2.0  ...              0              0   
1          9.0           5.0    1.0  ...              0              0   
2          9.0           4.0    1.0  ...              0              0   
3          9.0           3.0    0.0  ...              0              0   
4          9.0           2.0    0.0  ...              0              0   
...        ...           ...    ...  ...            ...            ...   
626278     1.0           1.0    0.0  ...              0              0   
626279     1.0           4.0    3.0  ...              0              0   
626280     1.0           3.0    2.0  ...              0              0   
626281     1.0           2.0    1.0  ...              0              0   
626282     1.0           1.0    0.0  ...              0              0   

        prev_pitch_KN  prev_pitch_NB  prev_pitch_SI  prev_pitch_SL  \
0                   0              0              0              1   
1                   0              0              1              0   
2                   0              0              0              0   
3                   0              0              1              0   
4                   0              0              1              0   
...               ...            ...            ...            ...   
626278              0              1              0              0   
626279              0              0              0              0   
626280              0              0              0              0   
626281              0              0              0              0   
626282              0              1              0              0   

        pitcher_throws_L  pitcher_throws_R  batter_stands_L  batter_stands_R  
0                      0                 1                1                0  
1                      0                 1                1                0  
2                      0                 1                1                0  
3                      0                 1                1                0  
4                      0                 1                1                0  
...                  ...               ...              ...              ...  
626278                 0                 1                1                0  
626279                 0                 1                0                1  
626280                 0                 1                0                1  
626281                 0                 1                0                1  
626282                 0                 1                0                1  

[622773 rows x 29 columns]

In [15]:
categoricalMask = data.dtypes==object
categoricalCols = data.columns[categoricalMask].tolist()
categoricalCols

['pitch_type']

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data[categoricalCols] = data[categoricalCols].apply(lambda col: le.fit_transform(col))

## Multi-Pitch Classification

In [17]:
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix

features = data.columns.tolist()[1:]
X = data[features]
y = data["pitch_type"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8)

In [18]:
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 9).fit(X_train, y_train) 
dtree_predictions = dtree_model.predict(X_test) 
accuracy = dtree_model.score(X_test, y_test)
cm = confusion_matrix(y_test, dtree_predictions) 
print(cm)
print(accuracy)

[[  634     3     0   459 10412     0    11   736     1     0   811   679]
 [   84     2     0   300  9418     0    27   346     0     0   444   428]
 [    0     0     0     0    11     0     0     0     0     0     0     0]
 [  220     1     0  1623  5146     0    45   317     0     0   364   235]
 [  383     4     0  1049 38540     0   324   951     1     0   506  3296]
 [    0     0     0     0     3     0     0     0     0     0     2     0]
 [   14     0     0    30  1141     0   392    79     1     0    71   116]
 [  183     2     0   312  6724     0    45  2250     0     0     0  1035]
 [   29     1     0    81  2231     0     5    92     2     0    61   108]
 [    0     0     0     0    33     0     0     1     0     0     0     0]
 [  264     3     0   267  5209     0    39     0     0     0  3185   673]
 [  107     3     0   234 15301     0    80   981     0     0   989  4365]]
0.40940146923046045


In [19]:
'''
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test) 
  
# model accuracy for X_test   
accuracy = svm_model_linear.score(X_test, y_test) 
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print(accuracy)
print(cm)
'''

"\nfrom sklearn.svm import SVC \nsvm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) \nsvm_predictions = svm_model_linear.predict(X_test) \n  \n# model accuracy for X_test   \naccuracy = svm_model_linear.score(X_test, y_test) \n  \n# creating a confusion matrix \ncm = confusion_matrix(y_test, svm_predictions) \nprint(accuracy)\nprint(cm)\n"

In [20]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train) 
  
# accuracy on X_test 
accuracy = knn.score(X_test, y_test) 
print(accuracy) 
  
# creating a confusion matrix 
knn_predictions = knn.predict(X_test)  
cm = confusion_matrix(y_test, knn_predictions) 

0.34067680944161216


## Fastball/No Fastball Classification

1 = Fastball, 0 = other pitch

In [21]:
fbData.head()

pitch_type  bat_score  fld_score  on_3b  on_2b  on_1b  outs_when_up  \
0           0        2.0        2.0    0.0    0.0    1.0           2.0   
1           0        2.0        2.0    0.0    0.0    1.0           2.0   
2           0        2.0        2.0    0.0    0.0    1.0           2.0   
3           0        2.0        2.0    0.0    0.0    1.0           2.0   
4           0        2.0        2.0    0.0    0.0    1.0           2.0   

   inning  pitch_number  balls  ...  prev_pitch_FT  prev_pitch_KC  \
0     9.0           6.0    2.0  ...              0              0   
1     9.0           5.0    1.0  ...              0              0   
2     9.0           4.0    1.0  ...              0              0   
3     9.0           3.0    0.0  ...              0              0   
4     9.0           2.0    0.0  ...              0              0   

   prev_pitch_KN  prev_pitch_NB  prev_pitch_SI  prev_pitch_SL  \
0              0              0              0              1   
1              0              0              1              0   
2              0              0              0              0   
3              0              0              1              0   
4              0              0              1              0   

   pitcher_throws_L  pitcher_throws_R  batter_stands_L  batter_stands_R  
0                 0                 1                1                0  
1                 0                 1                1                0  
2                 0                 1                1                0  
3                 0                 1                1                0  
4                 0                 1                1                0  

[5 rows x 29 columns]

In [22]:
fbData["pitch_type"].value_counts()

0    344264
1    278509
Name: pitch_type, dtype: int64

In [23]:
features = fbData.columns.tolist()[1:]
X = fbData[features]
y = fbData["pitch_type"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8)

In [24]:
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 6).fit(X_train, y_train) 
dtree_predictions = dtree_model.predict(X_test) 
accuracy = dtree_model.score(X_test, y_test)
cm = confusion_matrix(y_test, dtree_predictions) 
print(cm)
print(accuracy)

[[54583 14492]
 [35932 19548]]
0.5951667937858778


In [25]:
#### from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 14).fit(X_train, y_train) 
  
# accuracy on X_test 
accuracy = knn.score(X_test, y_test) 

  
# creating a confusion matrix 
knn_predictions = knn.predict(X_test)  
cm = confusion_matrix(y_test, knn_predictions) 
print(cm)
print(accuracy)

[[51786 17289]
 [34711 20769]]
0.5825137489462486


In [26]:

'''
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test) 
  
# model accuracy for X_test   
accuracy = svm_model_linear.score(X_test, y_test) 
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print(accuracy)
print(cm)
'''

"\nfrom sklearn.svm import SVC \nsvm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) \nsvm_predictions = svm_model_linear.predict(X_test) \n  \n# model accuracy for X_test   \naccuracy = svm_model_linear.score(X_test, y_test) \n  \n# creating a confusion matrix \ncm = confusion_matrix(y_test, svm_predictions) \nprint(accuracy)\nprint(cm)\n"

In [27]:
from keras.utils import to_categorical
num_classes=2
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

Using TensorFlow backend.
/home/parker/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/parker/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/parker/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/parker/.local/lib/python3.6/site-packages/tensorflow/python

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

model = Sequential()

model.add(Dense(20, input_shape=(len(features),), activation='relu', name='fc1'))
model.add(Dense(50, activation='relu', name='fc2'))
model.add(Dense(20, activation='relu', name='fc3'))
model.add(Dense(num_classes, activation='softmax', name='output'))

optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, verbose=2, batch_size=5, epochs=200)

W0213 16:05:28.561901 140212801177408 deprecation_wrapper.py:119] From /home/parker/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.



Epoch 1/200
 - 100s - loss: 0.6563 - accuracy: 0.5919
Epoch 2/200
 - 99s - loss: 0.6508 - accuracy: 0.5994
Epoch 3/200
 - 100s - loss: 0.6500 - accuracy: 0.6013
Epoch 4/200
 - 100s - loss: 0.6496 - accuracy: 0.6014
Epoch 5/200
 - 100s - loss: 0.6491 - accuracy: 0.6023
Epoch 6/200
 - 124s - loss: 0.6491 - accuracy: 0.6021
Epoch 7/200
 - 135s - loss: 0.6489 - accuracy: 0.6024
Epoch 8/200
 - 147s - loss: 0.6490 - accuracy: 0.6028
Epoch 9/200
 - 148s - loss: 0.6489 - accuracy: 0.6029
Epoch 10/200
 - 147s - loss: 0.6489 - accuracy: 0.6032
Epoch 11/200
 - 145s - loss: 0.6489 - accuracy: 0.6033
Epoch 12/200
 - 147s - loss: 0.6487 - accuracy: 0.6032
Epoch 13/200
 - 149s - loss: 0.6488 - accuracy: 0.6032
Epoch 14/200
 - 142s - loss: 0.6487 - accuracy: 0.6034
Epoch 15/200
 - 139s - loss: 0.6489 - accuracy: 0.6030
Epoch 16/200
 - 146s - loss: 0.6488 - accuracy: 0.6032
Epoch 17/200
 - 143s - loss: 0.6488 - accuracy: 0.6032
Epoch 18/200
 - 142s - loss: 0.6487 - accuracy: 0.6032
Epoch 19/200


In [ ]:
results = model.evaluate(X_test, y_test)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))